#------------------------------------------------------------#
#     CI Build Configuration for master branch pre-release   #
#------------------------------------------------------------#
version: "{build}"
image:
  - Visual Studio 2019
  - Ubuntu
configuration: Release
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  GITHUB_TOKEN:
    secure: o19fsTCbpIvyHbJfTaImgMr3OI6RHg2J+UdelQ1BIsc4o01+rCLuMc0lO+bhWL53
  CODECOV_TOKEN:
    secure: 2/6E5a1yzv5Wp1yRpHGDybeKyjdyJlO2xiRxuT4TBGBJcbSfjOrMRsFpMd/X334f
  NUGET_TOKEN:
    secure: ZDvc2hL3H+4ubTi1cibTM+XeOJVXEzhuMCnDxOL8Hs2e9unfRUHrCwYC52IVjXjh
  APPVEYOR_TOKEN:
    secure: wVt1RgJAnhNTyIjtK9yFkQbEEM+fBk1TLUzo0j3pe2U=
# Do not build feature branch with open Pull Requests
# skip_branch_with_pr: true
nuget:
  account_feed: true
build_script:
  - sh: nuget sources Add -Name "MyNuget" -Source https://api.nuget.org/v3/index.json
  - sh: chmod +x build.sh
  - sh: ./build.sh
  - ps: .\build.ps1
test: off