#------------------------------------------------------------#
#     CI Build Configuration for master branch pre-release   #
#------------------------------------------------------------#
version: 1.0.{build}
image:
  - Visual Studio 2017
  - Previous Ubuntu1804
configuration: Release
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  GITHUB_TOKEN:
    secure: o19fsTCbpIvyHbJfTaImgMr3OI6RHg2J+UdelQ1BIsc4o01+rCLuMc0lO+bhWL53
  CODECOV_TOKEN:
    secure: 2/6E5a1yzv5Wp1yRpHGDybeKyjdyJlO2xiRxuT4TBGBJcbSfjOrMRsFpMd/X334f
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
build_script:
  - sh: chmod +x build.sh
  - sh: ./build.sh
  - ps: .\build.ps1
test: off
artifacts:
- path: '.\artifacts\**\*.nupkg'
deploy:
  - provider: NuGet
    name: Nuget feed
    on:
      #branch: master
      appveyor_repo_tag: true
    api_key:
      secure: LxvD0QqULNgY5XtjQPrBlvQDOVacEkfkZILXVJbY2YPpwSQJLkbXF8QYtx7EMtL6
    skip_symbols: false
    artifact: /.*\.nupkg/

