#------------------------------------------------------------#
#     CI Build Configuration for master branch pre-release   #
#------------------------------------------------------------#
version: "{build}"
image:
  - Visual Studio 2022
  - Ubuntu
configuration: Release
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  CODECOV_TOKEN:
    secure: 2/6E5a1yzv5Wp1yRpHGDybeKyjdyJlO2xiRxuT4TBGBJcbSfjOrMRsFpMd/X334f
  NUGET_TOKEN:
    secure: OE/m5FgzlPwKm1+GYsvHkWqLvOGE6jnVJabPWy/O8XH3re/eSDilUc8cewoO2ZlI
  APPVEYOR_TOKEN:
    secure: wVt1RgJAnhNTyIjtK9yFkQbEEM+fBk1TLUzo0j3pe2U=
# Do not build feature branch with open Pull Requests
# skip_branch_with_pr: true
build_script:
  - sh: nuget sources Add -Name "MyNuget" -Source https://api.nuget.org/v3/index.json
  - sh: chmod +x build.sh
  - sh: ./build.sh
  - ps: (& cmd /c); [console]::OutputEncoding = New-Object System.Text.UTF8Encoding; & .\build.ps1
test: off 
